language: node-js

node-js:
    - "12"

cache:
    yarn: true

install:
    - yarn global add ynpx

branches:
    only:
        - master

after_success:
    - git remote set-url origin https://${GH_TOKEN}@github.com:${TRAVIS_REPO_SLUG}.git
    - git checkout master
    - git pull origin master

git:
    depth: 5

deploy:
    provider: script
    email: $EMAIL_ADDRESS
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    keep_history: true
    script: "ynpx lerna version --exact && git push --follow-tags && npx lerna publish --yes from-git"
    on:
        branch: master
