#!/bin/bash
set -e
echo "📦  Publishing latest release..."

# Note: try-publish should exit cleanly if it detects a duplicate.
# published version
$(npm bin)/lerna exec --concurrency 1 -- $(pwd)/scripts/try-publish
